### ISSUE TITLE
This program does not generate any output relating to my children

### ISSUE THREAD

**Issue by thessem** [jh69/biogenerator#1]
Issue: My children are the most important thing to me, as a paleo-dad and a blogger, but this program refuses to mention them in my bio. This is outrageous. I love my children, why don't you?

Steps to reproduce: You're obviously not ready to reproduce because you're oppressing the existence of the lifechanging feelings of loving and nurturing that overwhelm you when you create life.

**Comment by jh69** [comment]
u mf.
